site_name: SOT ConectaFapes
site_url: https://leds-conectafapes
theme:
  name: material
  features:
    - navigation.indexes
  favicon: assets/fapesLogo.svg
  font:
    text: Abel
    code: Red Hat Mono
  logo: assets/fapesLogo.svg
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: grey
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - https://unpkg.com/bpmn-js@18.2.0/dist/assets/bpmn-js.css
  - https://unpkg.com/bpmn-js@18.2.0/dist/assets/diagram-js.css
  - https://unpkg.com/bpmn-js@18.2.0/dist/assets/bpmn-font/css/bpmn.css
  - extra.css

extra_javascript:
  - https://unpkg.com/bpmn-js@18.2.0/dist/bpmn-navigated-viewer.production.min.js
  - javascripts/bpmn-loader.js

plugins:
  - search

nav:
  - index.md
  - Domínios: 
      - D001 - Edição de Perfil:
        - dominios/edicao-de-perfil/README.md
      - D002 - Gestão de Equipe:
        - dominios/gestao-de-equipe/README.md
        - dominios/gestao-de-equipe/diagrama-BPMN-bolsista.md
        - dominios/gestao-de-equipe/diagrama-BPMN-voluntario.md
      - D003 - Acompanhamento de Projeto:
        - dominios/acompanhamento-de-projeto/README.md
      - D004 - Prestação de Contas:
        - dominios/prestacao-de-contas/README.md
      - D005 - Gerar Pagamentos:
        - dominios/gerar-pagamentos/README.md
      - D006 - Gestão de Editais:
        - dominios/gestao-de-editais/README.md
      - D007 - Gestão de Modalidades / Níveis de Bolsa:
        - dominios/gestao-modalidades/README.md
      - D008 - Captação de Projetos:
        - dominios/captacao-de-projetos/README.md